{
 "title": "Pulsar / Overview By Broker",
 "description": "Overview of Pulsar Cluster",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "broker",
    "query": {
     "query": "label_values(pulsar_msg_backlog, kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{job=\"zookeeper\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Bookies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{job=\"bookkeeper\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Brokers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{job=\"broker\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Proxies",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(up{job=\"proxy\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_storage_size{job=~\"broker\"}) by (cluster)"
    }
   ]
  },
  {
   "title": "Backlog",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pulsar_msg_backlog{job=~\"broker\"}) by (cluster)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * ( 1 - \n   ( sum(increase(node_cpu_seconds_total{mode=\"idle\"}[1m]))\n    / \n   sum(increase(node_cpu_seconds_total[1m]))\n  )\n)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Zookeeper Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * count(up{job=\"zookeeper\"} == 1) / count(up{job=\"zookeeper\"})"
    }
   ]
  },
  {
   "title": "Bookies Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * count(up{job=\"bookkeeper\"} == 1) / count(up{job=\"bookkeeper\"})"
    }
   ]
  },
  {
   "title": "Brokers Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * count(up{job=\"broker\"} == 1) / count(up{job=\"broker\"})"
    }
   ]
  },
  {
   "title": "Proxies Up",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * count(up{job=\"proxy\"} == 1) / count(up{job=\"proxy\"})"
    }
   ]
  },
  { "title": "Messaging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Messaging Storage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pulsar_storage_size{job=~\"broker\",kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    },
    {
     "expr": "sum(pulsar_storage_size{job=~\"broker\",kubernetes_pod_name=~\"$broker\"}) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Message Rate (msg/s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_rate_in{job=~\"broker\"}) by (cluster)",
     "legendFormat": "Total In"
    },
    {
     "expr": "sum(pulsar_rate_in{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }} - In"
    },
    {
     "expr": "sum(pulsar_rate_out{job=~\"broker\"}) by (cluster)",
     "legendFormat": "Total Out"
    },
    {
     "expr": "sum(pulsar_rate_out{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }} - Out"
    }
   ]
  },
  {
   "title": "Top 10  topics backlog",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": " topk(10, sum(pulsar_msg_backlog{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name,topic))",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Messaging Backlog",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_msg_backlog{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    },
    {
     "expr": "sum(pulsar_msg_backlog{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_throughput_in{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }} - In"
    },
    {
     "expr": "sum(pulsar_throughput_in{job=~\"broker\"}) by (cluster)",
     "legendFormat": "Total In"
    },
    {
     "expr": "sum(pulsar_throughput_out{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }} - Out"
    },
    {
     "expr": "sum(pulsar_throughput_out{job=~\"broker\"}) by (cluster)",
     "legendFormat": "Total Out"
    }
   ]
  },
  {
   "title": "Subscription Unacked Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_subscription_unacked_messages{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) by (cluster)",
     "legendFormat": "Total In"
    },
    {
     "expr": "sum(pulsar_subscription_unacked_messages{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }} - In"
    }
   ]
  },
  {
   "title": "Producers Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_producers_count{job=~\"broker\",  kubernetes_pod_name=~\"$broker\"}) by (cluster)",
     "legendFormat": "Total In"
    },
    {
     "expr": "sum(pulsar_producers_count{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }} - In"
    }
   ]
  },
  {
   "title": "Top 10  Topics Unacked",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": " topk(10, sum(pulsar_subscription_unacked_messages{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) by (topic,kubernetes_pod_name))",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Consumers Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_consumers_count{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) by (cluster)",
     "legendFormat": "Total In"
    },
    {
     "expr": "sum(pulsar_consumers_count{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }} - In"
    }
   ]
  },
  {
   "title": "Subscriptions Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_subscriptions_count{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }} - In"
    },
    {
     "expr": "sum(pulsar_subscriptions_count{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) by (cluster)",
     "legendFormat": "Total In"
    }
   ]
  },
  {
   "title": "Messages I/O (1d)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pulsar_in_messages_total{kubernetes_pod_name=~\"$broker\"}[1d])) by (cluster)",
     "legendFormat": "Total In"
    },
    {
     "expr": "sum(increase(pulsar_in_messages_total{kubernetes_pod_name=~\"$broker\"}[1d])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}} - In"
    },
    {
     "expr": "sum(increase(pulsar_out_messages_total{kubernetes_pod_name=~\"$broker\"}[1d])) by (cluster)",
     "legendFormat": "Total Out"
    },
    {
     "expr": "sum(increase(pulsar_out_messages_total{kubernetes_pod_name=~\"$broker\"}[1d])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }} - Out"
    }
   ]
  },
  {
   "title": "Bytes I/O (1d)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pulsar_in_bytes_total{kubernetes_pod_name=~\"$broker\"}[1d])) by (cluster)",
     "legendFormat": "Total In"
    },
    {
     "expr": "sum(increase(pulsar_in_bytes_total{kubernetes_pod_name=~\"$broker\"}[1d])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }} - In"
    },
    {
     "expr": "sum(increase(pulsar_out_bytes_total{kubernetes_pod_name=~\"$broker\"}[1d])) by (cluster)",
     "legendFormat": "Total Out"
    },
    {
     "expr": "sum(increase(pulsar_out_bytes_total{kubernetes_pod_name=~\"$broker\"}[1d])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }} - Out"
    }
   ]
  },
  {
   "title": "Avg In Msg (1d)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pulsar_in_bytes_total[1d]))/sum(increase(pulsar_in_messages_total[1d]))"
    }
   ]
  },
  {
   "title": "Top 10  Topics Storage",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": " topk(10, sum(pulsar_storage_size{job=~\"broker\",kubernetes_pod_name=~\"$broker\"}) by (topic,kubernetes_pod_name))",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Avg Out Msg (1d)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(pulsar_out_bytes_total[1d]))/sum(increase(pulsar_out_messages_total[1d]))"
    }
   ]
  },
  {
   "title": "Offloaded Size Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_offloaded_size{kubernetes_pod_name=~\"$broker\"}) by (cluster)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(pulsar_storage_offloaded_size{kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Redelivery Rate (msg/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_subscription_msg_rate_redeliver{kubernetes_pod_name=~\"$broker\"}) by (cluster)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(pulsar_subscription_msg_rate_redeliver{kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Top 10  Topics Offload Size",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": " topk(10, sum(pulsar_storage_offloaded_size{job=~\"broker\", kubernetes_pod_name=~\"$broker\"}) by (topic,kubernetes_pod_name))",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * (1 - (sum(increase(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance)\n/ \nsum(increase(node_cpu_seconds_total[1m])) by (instance)))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Node Memory Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes * 100 ",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}