{
 "title": "JVM Metrics",
 "description": "JVM Related Metrics",
 "tags": [ "jvm" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Pulsar Cluster",
    "query": {
     "query": "pulsar_version_info{cluster=~\".+\"}"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": "jvm_memory_bytes_used{job=~\".+\"}"
   },
   {
    "name": "kubernetes_pod_name",
    "label": "Instance",
    "query": "jvm_memory_bytes_used{cluster=~\"$cluster\",job=~\"$job\", kubernetes_pod_name=~\".+\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "$job - $kubernetes_pod_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "kubernetes_pod_name",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{kubernetes_pod_name=~\"$kubernetes_pod_name\"}[30s]) * 100\n\n",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_committed{kubernetes_pod_name=~\"$kubernetes_pod_name\"})",
     "legendFormat": "Heap size"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{kubernetes_pod_name=~\"$kubernetes_pod_name\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{kubernetes_pod_name=~\"$kubernetes_pod_name\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Direct Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_direct_bytes_used{kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_direct_bytes_max{kubernetes_pod_name=~\"$kubernetes_pod_name\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{kubernetes_pod_name=~\"$kubernetes_pod_name\"}[30s]))",
     "legendFormat": "Pause"
    }
   ]
  }
 ]
}