
# ---          
# apiVersion: litmuschaos.io/v1alpha1
# kind: ChaosEngine
# metadata:
#   name: engine-nginx-cpu-hog
# spec:
#   engineState: "active"
#   annotationCheck: "false"
#   # AUT details
#   appinfo:
#     appns: "litmus"
#     applabel: "app=nginx"
#     appkind: "deployment"
#   chaosServiceAccount: pod-delete-sa
#   experiments:
#   - name: pod-cpu-hog
#     spec:
#       components:
#         env:
#         - name: TOTAL_CHAOS_DURATION
#           value: "60"
# ---          
# apiVersion: litmuschaos.io/v1alpha1
# kind: ChaosEngine
# metadata:
#   name: engine-nginx-corrupt
# spec:
#   engineState: "active"
#   annotationCheck: "false"
#   # AUT details
#   appinfo:
#     appns: "litmus"
#     applabel: "app=nginx"
#     appkind: "deployment"dmpdev2use1
#   chaosServiceAccount: pod-delete-sa
#   experiments:
#   - name: pod-network-corruption
#     spec:
#       components:
#         env:
#         - name: TOTAL_CHAOS_DURATION
#           value: "60"
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
spec:
  engineState: "active"
  annotationCheck: "false"
  # AUT details
  appinfo:
    appns: "litmus"
    applabel: "app=nginx"
    appkind: "deployment"
  chaosServiceAccount: pod-delete-sa
  experiments:
  - name: pod-delete
    spec:
      components:
        env:
        # name of the target node
        - name: TOTAL_CHAOS_DURATION
          value: "120"
  # - name: pod-network-latency
  #   spec:
  #     components:
  #       env:
  #       - name: TOTAL_CHAOS_DURATION
  #         value: "60"
  #       - name: NETWORK_LATENCY
  #         value: "2000"          
---
