apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            ephemeral-storage: 500M
            memory: 100M
          limits:
            cpu: 100m
            ephemeral-storage: 800M
            memory: 100M
---
apiVersion: v1
kind: Service
metadata:
  name: "nginx-service"
  labels:
    app: nginx
spec:
  ports:
  - name: http
    port: 8090
    targetPort: 80
  selector:
    app: nginx
